version: "3"

services:
  nginx:
    image: nginx:alpine
    container_name: superset_frontend_nginx
    ports:
      - "3031:3031"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
    networks:
      - superset_network_external

networks:
  superset_network_external:
    external: true
    name: superset_default # Make sure this matches your existing Superset network name
